Repository redmod-team/profit, pull requests merged in 2021-04, with the labels that each got.

#92 ZeroMQ, Slurm, Documentation & more
  CONTRIBUTING.md
  README.md
  doc/conf.py
  doc/config.rst
  doc/index.rst
  doc/modules.rst
  doc/profit.rst
  doc/profit.run.rst
  doc/profit.sur.backend.rst
  doc/profit.sur.rst
  doc/profit.ui.rst
  doc/profit.uq.rst
  doc/profit.util.rst
  examples/mockup/simple/profit.yaml
  examples/mockup/simple/template/mockup.in
  examples/mockup/simple/template/mockup.py
  examples/mockup/study/slurm.yaml
  profit/config.py
  profit/defaults.py
  profit/main.py
  profit/run/__init__.py
  profit/run/default.py
  profit/run/runner.py
  profit/run/slurm.py
  profit/run/worker.py
  profit/run/zeromq.py
  profit/util/util.py
  setup.cfg
  tests/mockup/mockup_custom_worker.py
  tests/mockup/study/custom_post.py
  tests/run/interactive.ipynb
  tests/run/numpy.yaml
  tests/run/test_components.py
Labels: project

#93 UI: add fits
  profit/main.py
  profit/ui/__init__.py
  profit/ui/app.py
Labels: project

#95 Polishing Slurm
  doc/config.rst
  profit/config.py
  profit/run/slurm.py
  profit/run/zeromq.py
  profit/util/variable_kinds.py
Labels: project

#97 Docstrings and improved Fit
  doc/config.rst
  doc/draft_loop.py
  doc/gp_custom_test.py
  draft/Active_BBQ.py
  draft/Active_MGP.py
  draft/fortran_vs_numpy/bench_fortran_numpy.py
  draft/optim/draft_optim.py
  draft/test_linalg.py
  examples/GP_Regression/profit/GP_profit.py
  profit/draft/Random_GP.py
  profit/fit.py
  profit/sur/backend/gp_functions.py
  profit/sur/backend/gp_functions_old.py
  profit/sur/backend/python_kernels.py
  profit/sur/gaussian_process.py
  profit/sur/gp.py
  profit/sur/sur.py
  tests/active_learning/study_1D/profit_1D.yaml
  tests/active_learning/study_2D/profit_2D.yaml
  tests/active_learning/template/mockup_1D.in
  tests/active_learning/template/mockup_1D.py
  tests/active_learning/template/mockup_2D.in
  tests/active_learning/template/mockup_2D.py
  tests/active_learning/test_active_learning.py
  tests/mockup/simulation_files/mockup_1D.py
  tests/mockup/simulation_files/mockup_2D.py
  tests/mockup/simulation_files/mockup_independent.py
  tests/mockup/simulation_files/mockup_multi_output.py
  tests/mockup/study/template/mockup_1D.py
  tests/mockup/study/template/mockup_2D.py
  tests/mockup/study/template/mockup_independent.py
  tests/mockup/study_1D/profit_1D.yaml
  tests/mockup/study_2D/profit_2D.yaml
  tests/mockup/study_custom_post/custom_post.py
  tests/mockup/study_custom_post/profit_custom_post.yaml
  tests/mockup/study_custom_worker/mockup_custom_worker.py
  tests/mockup/study_custom_worker/profit_custom_worker.yaml
  tests/mockup/study_independent/profit_independent.yaml
  tests/mockup/study_multi_output/profit_multi_output.yaml
  tests/mockup/template_1D/mockup_1D.in
  tests/mockup/template_1D/mockup_1D.py
  tests/mockup/template_2D/mockup_2D.in
  tests/mockup/template_2D/mockup_2D.py
  tests/mockup/template_independent/mockup_independent.json
  tests/mockup/template_independent/mockup_independent.py
  tests/mockup/template_multi_output/mockup_multi_output.in
  tests/mockup/template_multi_output/mockup_multi_output.py
  tests/mockup/test_mockup.py
  tests/sur/test_gp.py
  tests/sur/test_kernels.py
Labels: enhancement

#98 UI update
  profit/ui/app.py
  setup.cfg
Labels: bug, enhancement
